#!/usr/bin/env python3
# Orbital Study — Copyright (c) 2026 Antonio Juarez (@antoniojl16). All rights reserved. See LICENSE.
"""Builds world-map.js, the Astrocartography base map, from Natural Earth (public domain).

    python3 tools/build-world-map.py [work-dir] [land-scale] [simplify-meters]

Defaults: 1:110m land (the lightest Natural Earth scale), not simplified further.

Needs Node.js (runs mapshaper through npx) and network access to download the sources:
  - ne_<LAND_SCALE>_admin_0_countries     land, one ring set per country
  - ne_50m_admin_1_states_provinces_lines   state/province lines (the 1:50m set covers
    exactly the countries in STATE_COUNTRIES)
  - ne_<LAND_SCALE>_lakes                major lakes (scalerank <= LAKE_MAX_SCALERANK)
Each layer is simplified with mapshaper (topology-preserving, so neighbouring
countries keep sharing exactly the same border) to about SIMPLIFY_METERS (0 = not
simplified), then
stored to 0.01° as delta-encoded integers — see decodeWorldRing in
astrocartography.js.
"""
import json, os, subprocess, sys, urllib.request

SOURCE = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/"
LAND_SCALE = sys.argv[2] if len(sys.argv) > 2 else "110m"
SIMPLIFY_METERS = int(sys.argv[3]) if len(sys.argv) > 3 else 0
LAKE_MAX_SCALERANK = 3
STATE_COUNTRIES = {"United States of America", "Canada", "China", "Russia", "India", "Australia", "Brazil", "Indonesia", "South Africa"}

work = sys.argv[1] if len(sys.argv) > 1 else "/tmp/orbital-study-map"
os.makedirs(work, exist_ok=True)
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def download(name):
    path = os.path.join(work, name + ".geojson")
    if not os.path.exists(path):
        print("downloading", name)
        urllib.request.urlretrieve(SOURCE + name + ".geojson", path)
    return path

def simplify(path, out, extra=()):
    simplify = ["-simplify", f"interval={SIMPLIFY_METERS}", "keep-shapes"] if SIMPLIFY_METERS else []
    subprocess.run(["npx", "--yes", "mapshaper", path, *extra, *simplify,
                    "-o", "format=geojson", "precision=0.01", "force", out], check=True)
    return json.load(open(out))["features"]

def parts(geometry):
    if not geometry:
        return []
    kind, coords = geometry["type"], geometry["coordinates"]
    if kind == "Polygon":
        return coords
    if kind == "MultiPolygon":
        return [ring for polygon in coords for ring in polygon]
    if kind == "LineString":
        return [coords]
    if kind == "MultiLineString":
        return coords
    return []

def encode(points):
    """[lon, lat, ...] in 0.01° units: the first point absolute, then differences."""
    out, px, py = [], 0, 0
    for lon, lat in points:
        x, y = round(lon * 100), round(lat * 100)
        if out and x == px and y == py:
            continue
        out += [x - px, y - py]
        px, py = x, y
    return out

countries = simplify(download(f"ne_{LAND_SCALE}_admin_0_countries"), os.path.join(work, "land.json"), ["-filter-fields", "NAME"])
land = [encode(ring) for feature in countries for ring in parts(feature["geometry"])]
lakes_path = download(f"ne_{LAND_SCALE}_lakes")
lakes = simplify(lakes_path, os.path.join(work, "lakes.json"), ["-filter", f"scalerank <= {LAKE_MAX_SCALERANK}"])
lakes = [encode(ring) for feature in lakes for ring in parts(feature["geometry"])[:1]]  # outer rings only
states = simplify(download("ne_50m_admin_1_states_provinces_lines"), os.path.join(work, "states.json"))
states = [encode(line) for feature in states for line in parts(feature["geometry"])]

def js(rings):
    return "[" + ",\n".join(json.dumps(r, separators=(",", ":")) for r in rings if len(r) >= 4) + "]"

header = """// Orbital Study's Astrocartography base map — generated by tools/build-world-map.py; don't hand-edit.
// Natural Earth (public domain, naturalearthdata.com): 1:%s admin-0 countries (land) and
// major lakes, and 1:50m admin-1 state/province lines (%s)%s.
// Each ring or line is [lon, lat, ...] in 0.01° units, the first point absolute and the
// rest as differences from the previous point (decodeWorldRing, astrocartography.js).
// Loaded on demand the first time a map is shown (acgLoadWorldMap).
""" % (LAND_SCALE, ", ".join(sorted(STATE_COUNTRIES)), f", simplified to ~{SIMPLIFY_METERS / 1000:g} km" if SIMPLIFY_METERS else "")
body = f"const WORLD_MAP = {{\nland: {js(land)},\nlakes: {js(lakes)},\nstates: {js(states)}\n}};\nacgWorldMapLoaded();\n"
with open(os.path.join(root, "world-map.js"), "w") as f:
    f.write(header + body)
print("world-map.js", os.path.getsize(os.path.join(root, "world-map.js")), "bytes;", len(land), "land rings,", len(lakes), "lakes,", len(states), "state lines")
