#!/usr/bin/env python3
# Orbital Study — Copyright (c) 2026 Antonio Juarez (@antoniojl16). All rights reserved. See LICENSE.
"""Builds roads.js, the Astrocartography map's main roads, from Natural Earth (public domain).

    python3 tools/build-roads.py [work-dir]

Source: ne_10m_roads (naciscdn.org/naturalearth/10m/cultural/ne_10m_roads.zip). Roads are
chosen by Natural Earth's own importance rank (scalerank, consistent worldwide — its
"type" field isn't): ranks 3–4 become the major tier, rank 5 the minor tier; ferries
are left out. Simplified with mapshaper (through npx) to ~1.5 km and stored like
world-map.js: [lon, lat, ...] in 0.01° units, the first point absolute and the rest as
differences (decodeWorldRing, astrocartography.js).
"""
import json, os, subprocess, sys, urllib.request, zipfile

work = sys.argv[1] if len(sys.argv) > 1 else "/tmp/orbital-study-roads"
os.makedirs(work, exist_ok=True)
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
archive = os.path.join(work, "ne_10m_roads.zip")
if not os.path.exists(archive):
    urllib.request.urlretrieve("https://naciscdn.org/naturalearth/10m/cultural/ne_10m_roads.zip", archive)
zipfile.ZipFile(archive).extractall(work)

def layer(expression, name):
    out = os.path.join(work, name + ".json")
    subprocess.run(["npx", "--yes", "mapshaper", os.path.join(work, "ne_10m_roads.shp"), "-filter", expression,
                    "-simplify", "interval=1500", "-o", "format=geojson", "precision=0.01", "force", out], check=True)
    lines = []
    for feature in json.load(open(out))["features"]:
        geometry = feature["geometry"]
        if not geometry:
            continue
        for line in [geometry["coordinates"]] if geometry["type"] == "LineString" else geometry["coordinates"]:
            encoded, px, py = [], 0, 0
            for lon, lat in line:
                x, y = round(lon * 100), round(lat * 100)
                if encoded and x == px and y == py:
                    continue
                encoded += [x - px, y - py]
                px, py = x, y
            if len(encoded) >= 4:
                lines.append(encoded)
    return lines

major = layer("scalerank <= 4 && featurecla != 'Ferry'", "major")
minor = layer("scalerank == 5 && featurecla != 'Ferry'", "minor")
js = lambda lines: "[" + ",\n".join(json.dumps(l, separators=(",", ":")) for l in lines) + "]"
header = """// Orbital Study's main roads for the Astrocartography map — generated by tools/build-roads.py;
// don't hand-edit. Natural Earth 1:10m roads (public domain, naturalearthdata.com):
// major = importance ranks 3–4, minor = rank 5; simplified to ~1.5 km, delta-encoded
// 0.01° [lon, lat, ...] lines (decodeWorldRing, astrocartography.js). Loaded the first
// time a map is zoomed in far enough to show roads (acgLoadRoads).
"""
with open(os.path.join(root, "roads.js"), "w") as f:
    f.write(header + f"const WORLD_ROADS = {{\nmajor: {js(major)},\nminor: {js(minor)}\n}};\nacgRoadsLoaded();\n")
print("roads.js", os.path.getsize(os.path.join(root, "roads.js")), "bytes;", len(major), "major,", len(minor), "minor lines")
