#!/usr/bin/env python3
# Orbital Study — Copyright (c) 2026 Antonio Juarez (@antoniojl16). All rights reserved. See LICENSE.
"""Builds epoch-precession.js, the precession table behind the Epoch Explorer's Human
Design view (the equinox drifting backwards through the gates).

    pip install pyerfa numpy
    python3 tools/build-epoch-precession.py

The equinox's place on the star-fixed mandala is 360° minus the ayanamsa: how far the
equinox has drifted from a fixed point among the stars. The drift (precession) comes
from the IAU's long-term precession model (Vondrák, Capitaine & Wallace 2011, A&A 534
A22; erratum A&A 541 C1), as implemented by ERFA (the open-source edition of the IAU's
SOFA library: eraLtpecl / eraLtpequ), which is valid for ±200,000 years. The fixed
point is the direction of the star Spica (as in the Lahiri ayanamsa), measured on the
mean ecliptic and equinox of date — no nutation.

The zero point is Human Design's own date for the 37 → 55 transition: 15 February 2027
22:10 UTC, when the equinox crosses 335.75° (the boundary between gates 37 and 55) —
an ayanamsa of exactly 24.25° then.

Output: the ayanamsa (degrees) every STEP years from START to END (Julian years of TT);
the app interpolates between them (a cubic; the drift is smooth).
"""
import math
import pathlib

import erfa
import numpy as np

START, END, STEP = -17000, 4000, 25
ANCHOR_UTC = (2027, 2, 15, 22, 10)
ANCHOR_AYANAMSA = 24.25
TT_MINUS_UTC = 69.184  # seconds (37 leap seconds + 32.184 s), as of 2027

ra, dec = math.radians(201.2982475), math.radians(-11.1613194)  # Spica, J2000 (ICRS)
spica = np.array([math.cos(dec) * math.cos(ra), math.cos(dec) * math.sin(ra), math.sin(dec)])


def spica_longitude(epj):
    """Spica's longitude (degrees) on the mean ecliptic and equinox of Julian epoch epj."""
    pole_ecliptic, pole_equator = erfa.ltpecl(epj), erfa.ltpequ(epj)
    x = np.cross(pole_equator, pole_ecliptic)
    x /= np.linalg.norm(x)
    y = np.cross(pole_ecliptic, x)
    return math.degrees(math.atan2(spica @ y, spica @ x))


def unwrapped(epochs):
    values, total, previous = [], None, None
    for epj in epochs:
        value = spica_longitude(epj)
        if previous is None:
            total = value
        else:
            total += (value - previous + 180) % 360 - 180
        previous = value
        values.append(total)
    return values


year, month, day, hour, minute = ANCHOR_UTC
dj1, dj2 = erfa.cal2jd(year, month, day)
anchor = erfa.epj(dj1, dj2 + (hour * 60 + minute) / 1440 + TT_MINUS_UTC / 86400)
epochs = list(range(START, END + STEP, STEP))
raw = unwrapped(epochs)
nearest = min(range(len(epochs)), key=lambda i: abs(epochs[i] - anchor))
at_anchor = raw[nearest] + (spica_longitude(anchor) - spica_longitude(epochs[nearest]) + 180) % 360 - 180
values = [value - at_anchor + ANCHOR_AYANAMSA for value in raw]

root = pathlib.Path(__file__).resolve().parent.parent
(root / "epoch-precession.js").write_text(
    "// Orbital Study — Copyright (c) 2026 Antonio Juarez (@antoniojl16). All rights reserved. See LICENSE.\n"
    "// Generated by tools/build-epoch-precession.py — don't edit by hand. The ayanamsa (degrees) every\n"
    f"// {STEP} Julian years (TT) from {START} (astronomical year numbering) to {END}: IAU long-term precession\n"
    "// (Vondrák et al. 2011) of the star Spica, anchored at 24.25° on 15 Feb 2027 22:10 UTC.\n"
    f"const EPOCH_PRECESSION = {{ start: {START}, step: {STEP}, anchorEpoch: {anchor:.8f}, values: [{','.join(f'{v:.6f}' for v in values)}] }};\n",
    encoding="utf-8",
)
print(f"Wrote epoch-precession.js: {len(values)} values; anchor epoch {anchor:.6f}")
