#!/usr/bin/env python3
# Orbital Study — Copyright (c) 2026 Antonio Juarez (@antoniojl16). All rights reserved. See LICENSE.
"""Builds places.js, the birth-location search's gazetteer, from GeoNames (CC BY 4.0).

    python3 tools/build-places.py [work-dir]

Downloads from download.geonames.org/export/dump/ (about 210 MB, cached in work-dir):
  - cities5000.zip        every populated place of 5,000+ people (or a seat of government)
  - admin1CodesASCII.txt  state/province names
  - countryInfo.txt       country names and main languages
  - alternateNamesV2.zip  used only to add each place's English name and its name in
                          the country's main language, where they differ (Köln ↔ Cologne)
Each place keeps its coordinates (4 decimals, ~10 m) and IANA time zone; places are
sorted by population so the search can stop at the first good matches.
"""
import io, json, os, sys, unicodedata, urllib.request, zipfile

SOURCE = "https://download.geonames.org/export/dump/"
work = sys.argv[1] if len(sys.argv) > 1 else "/tmp/orbital-study-places"
os.makedirs(work, exist_ok=True)
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def fetch(name):
    path = os.path.join(work, name)
    if not os.path.exists(path):
        print("downloading", name)
        urllib.request.urlretrieve(SOURCE + name, path)
    return path

def zipped_lines(name, member):
    with zipfile.ZipFile(fetch(name)) as archive, archive.open(member) as raw:
        yield from io.TextIOWrapper(raw, encoding="utf-8")

def fold(text):
    return "".join(c for c in unicodedata.normalize("NFKD", text) if not unicodedata.combining(c)).casefold()

def clean(text):
    return text.replace("|", " ").replace(";", " ").replace("\n", " ").strip()

countries, languages = {}, {}
for line in open(fetch("countryInfo.txt"), encoding="utf-8"):
    if line.startswith("#"):
        continue
    cols = line.rstrip("\n").split("\t")
    countries[cols[0]] = cols[4]
    languages[cols[0]] = (cols[15].split(",")[0].split("-")[0] or "en") if len(cols) > 15 else "en"

regions_by_code = {}
for line in open(fetch("admin1CodesASCII.txt"), encoding="utf-8"):
    code, name = line.split("\t")[:2]
    regions_by_code[code] = name

places = {}
for line in zipped_lines("cities5000.zip", "cities5000.txt"):
    c = line.rstrip("\n").split("\t")
    places[c[0]] = {"name": c[1], "cc": c[8], "region": regions_by_code.get(f"{c[8]}.{c[10]}", ""),
                    "lat": float(c[4]), "lon": float(c[5]), "zone": c[17], "pop": int(c[14] or 0)}

# Alternate names: per place, the preferred (else first) English and main-language names.
chosen = {}
for line in zipped_lines("alternateNamesV2.zip", "alternateNamesV2.txt"):
    c = line.rstrip("\n").split("\t")
    place = places.get(c[1])
    if not place or c[6] == "1" or c[7] == "1":  # skip colloquial and historic names
        continue
    language = c[2]
    if language not in ("en", languages.get(place["cc"], "en")):
        continue
    key = (c[1], language)
    preferred = c[4] == "1"
    if key not in chosen or (preferred and not chosen[key][1]):
        chosen[key] = (c[3], preferred)
for (geonameid, _), (name, _) in chosen.items():
    place = places[geonameid]
    aliases = place.setdefault("aliases", [])
    if fold(name) != fold(place["name"]) and all(fold(name) != fold(a) for a in aliases) and len(name) <= 60:
        aliases.append(name)

zones, regions = [], []
zone_index, region_index = {}, {}
def index(value, table, lookup):
    if value not in lookup:
        lookup[value] = len(table)
        table.append(value)
    return lookup[value]

rows = []
for place in sorted(places.values(), key=lambda p: -p["pop"]):
    if not place["zone"]:
        continue
    rows.append("|".join([
        clean(place["name"]), ";".join(clean(a) for a in place.get("aliases", [])), place["cc"],
        str(index(clean(place["region"]), regions, region_index)),
        f"{place['lat']:.4f}".rstrip("0").rstrip("."), f"{place['lon']:.4f}".rstrip("0").rstrip("."),
        str(index(place["zone"], zones, zone_index)), str(round(place["pop"] / 1000)),
    ]))

header = """// Orbital Study's birth-location gazetteer — generated by tools/build-places.py; don't hand-edit.
// Place data from GeoNames (geonames.org), licensed under Creative Commons Attribution 4.0
// (https://creativecommons.org/licenses/by/4.0/): populated places of 5,000+ people, with
// coordinates, IANA time zone, state/province, and English / local names where they differ.
// Rows: name|aliases (;-separated)|country code|region index|lat|lon|zone index|population (thousands),
// most populous first. Loaded on demand by place-search.js.
"""
data = {"zones": zones, "regions": regions, "countries": countries, "rows": "\n".join(rows)}
with open(os.path.join(root, "places.js"), "w", encoding="utf-8") as f:
    f.write(header + "const PLACES_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\nplacesLoaded();\n")
print("places.js", os.path.getsize(os.path.join(root, "places.js")), "bytes;", len(rows), "places,", len(zones), "zones,",
      sum(1 for p in places.values() if p.get("aliases")), "with aliases")
